#!/bin/sh

FILE=./src/IdrvPaths/Generated.idr

echo "module IdrvPaths.Generated"            > "$FILE"
echo ""                                     >> "$FILE"
echo "-- @generated by 'make'/'make build'" >> "$FILE"
echo "export"                               >> "$FILE"
echo "idrvLocation : String"                >> "$FILE"
echo "idrvLocation = \"${INSTALLDIR}\""     >> "$FILE"
echo ""                                     >> "$FILE"

