#!/bin/sh

FILE=./src/IdvPaths/Generated.idr

echo "module IdvPaths.Generated"            > "$FILE"
echo ""                                     >> "$FILE"
echo "-- @generated by 'make'/'make build'" >> "$FILE"
echo "export"                               >> "$FILE"
echo "idvLocation : String"                >> "$FILE"
echo "idvLocation = \"${INSTALLDIR}\""     >> "$FILE"
echo ""                                     >> "$FILE"

