#!/usr/bin/env bash

FILE=./backend/src/IdvPaths/Generated.idr

INSTALLDIR=${INSTALLDIR:-~/.idv}
IDRIS2=${IDRIS2:-~/.idris2/bin/idris2}
PACK_DIR=${PACK_DIR:-~/.pack}

echo "-- @generated by 'make'/'make build'"    > "$FILE"
echo "module IdvPaths.Generated"              >> "$FILE"
echo ""                                       >> "$FILE"
echo "export"                                 >> "$FILE"
echo "idvLocation : String"                   >> "$FILE"
echo "idvLocation = \"${INSTALLDIR}\""        >> "$FILE"
echo ""                                       >> "$FILE"
echo "export"                                 >> "$FILE"
echo "defaultIdris2Location : String"         >> "$FILE"
echo "defaultIdris2Location = \"${IDRIS2}\""  >> "$FILE"
echo ""                                       >> "$FILE"
echo "export"                                 >> "$FILE"
echo "defaultPackDirectory : String"          >> "$FILE"
echo "defaultPackDirectory = \"${PACK_DIR}\"" >> "$FILE"
echo ""                                       >> "$FILE"

