-- @generated by 'make'/'make build'
module IdvPaths.Generated

export
idvLocation : String
idvLocation = "~/.idv"

export
defaultIdris2Location : String
defaultIdris2Location = "~/.idris2/bin/idris2"

