
name: Idv tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mattpolzin2/idris-docker:nightly

    steps:
      - name: Install Dependencies
        run: apt-get update && apt-get -y install git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build & Install Idv
        run: make && make install
      - name: Run Golden tests
        run: INTERACTIVE_TESTS='' TEST_INSTALLDIR=~/test/.idv IDRIS2=/root/.idris2/bin/idris2 make test
      - name: Install w/ LSP
        run: |
          export PATH="$HOME/.idv/bin:$PATH"
          idv install 0.6.0 --lsp
          idv select 0.6.0
          echo "$(idris2 --version)"
          echo "$(which idris2-lsp)"
          test "$(idris2 --version)" = 'Idris 2, version 0.6.0-nightly'
          test "$(which idris2-lsp)" != ''
          echo "$(idris2-lsp --version)"
